dist: xenial
language: python

python:
  - 3.5
  - 3.6
  - &mainstream_python 3.7
  - &pypy3 pypy3.5-7.0.0

install:
  - pip install -r requirements/test.txt
  - pip install ./

script: pytest

after_success:
 - codecov

cache: pip

branches:
    only:
        - master
        - /^v\d+(\.\d+)*$/
