dist: xenial
language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - pypy3.5-6.0.0
  - pypy3.5-7.0.0

cache: pip

install:
  - pip install -r requirements/test.txt
  - pip install .

script: pytest

after_success:
 - codecov

branches:
    only:
        - master
        - /^v\d+(\.\d+)*$/
